services:
  - type: web
    name: itatech-os-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: itatech_os
      - key: CORS_ORIGIN_REGEX
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SUPERADMIN_KEY
        sync: false
